AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  App:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: serverless-qiita-team-template
      Runtime: go1.x 
      CodeUri: build
      Timeout: 60
      Environment:
        Variables:
          QIITA_ACCESS_TOKEN: xxxx
          QIITA_TEAM_NAME: example
          QIITA_TEAM_TEMPLATE_ID: 0
      Events:
        Schedule:
          Type: Schedule
          Properties:
            # TODO: To generalize
            Schedule: cron(0 1 ? * TUE *) # at 10:00 every Tuesday (JST)
